### ISSUE TITLE
P.6 typo "おけげで"→"おかげで"

### ISSUE THREAD

**Issue by h-yamane-sti** [gamasenninn/gihyo-ChatGPT#5]

**Comment by gamasenninn** [comment]
@h-yamane-sti 様。ご指摘、本当にありがとうございます。早急に正誤表に反映いたします。

**Comment by gamasenninn** [comment]
@h-yamane-sti 様。ご指摘部分を正誤表に反映いたしました。この件はクローズとさせていただいます。Typoなど発見の際はまたISSUEにあげていただければ幸いです。ありがとうございました。
