### ISSUE TITLE
typo: p.77 "Pythonisaための" → "Pythonisaのための"

### ISSUE THREAD

**Issue by h-yamane-sti** [gamasenninn/gihyo-ChatGPT#6]
「の」が抜けているように見受けられます。

**Comment by gamasenninn** [comment]
@h-yamane-sti 様。ご指摘、本当にありがとうございます。早急に正誤表に反映いたします。

**Comment by gamasenninn** [comment]
よくみたらPythonisaー＞Pythonistaも間違っていました。これも直します。

**Comment by gamasenninn** [comment]
@h-yamane-sti 様。ご指摘部分を正誤表に反映いたしました。この件はクローズとさせていただいます。Typoなど発見の際はまたISSUEにあげていただければ幸いです。ありがとうございました。
